spring.application.name=pet
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.profiles.active=database
logging.level.org.hibernate.SQL=DEBUG

# ?? ???? 30? ??
server.servlet.session.timeout=30m